apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    control-plane: {{ .Values.controlPlane }}
  name: kusionstack-controller-manager
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.managerReplicas }}
  selector:
    matchLabels:
      control-plane: {{ .Values.controlPlane }}
  template:
    metadata:
      labels:
        control-plane: {{ .Values.controlPlane }}
    spec:
      containers:
      - args:
        - --leader-elect
        - --cert-dir=/webhook-certs
        - --dns-name=kusionstack-controller-manager.{{ .Values.namespace }}.svc
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - -v=4
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      serviceAccountName: kusionstack-controller-manager
      terminationGracePeriodSeconds: 0
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs