# Default values for mykridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

managerReplicas: 3

project: operating
namespace: kusionstack-system
namespaceEnabled: true

controlPlane: kusionstack-operating

imageTag: v0.1.0-beta.0
imageRepo: kusionstack/operating
imagePullPolicy: IfNotPresent
managerReplicas: 3

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

commonLabels:
  app.kubernetes.io/part-of: operating




