{{- if .Values.namesapceEnabled -}}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    control-plane: {{ .Values.controlPlane }}
  name: {{ .Values.namespace }}
{{- end }}