# Default values for mykridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: kridge
namesapceEnabled: true

imageTag: v0.1.0-beta.3
proxyImage:
  repository: kusionstack/kridge-proxy
  pullPolicy: IfNotPresent

managerImage:
  repository: kusionstack/kridge-manager
  pullPolicy: IfNotPresent

initImage: kusionstack/kridge-init

managerResources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

proxyResources:
  cpu: 100m
  memory: 100Mi
  ephemeralStorage: 100Mi

shardingGroupVersionKinds:
  groupVersionKinds:
    kridge.kusionstack.io/v1alpha1:
    - '*'
    v1:
    - Pod
    - PersistentVolumeClaim
    - Service
    - ConfigMap
    - Endpoint
    apps/v1:
    - StatefulSet
    - ReplicaSet
    - ControllerRevision


