
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-operator-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: demo-operator-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - pods
  - services
  - events
  - leases
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-operator-role
subjects:
- kind: ServiceAccount
  name: demo-operator-serviceaccount
  namespace: {{ .Values.namespace }}
---
{{- if .Values.namesapceEnabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{- end }}